<?php

/* 

Copyright (C) 2015  Ulises Abel Arias García

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

function reporte_cdr_menu() {
  $items = array();

  $items['formularios/reporte-cdr'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Consulta de CDR', //page title
    'description' => 'Formulario de consulta de CDR',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('reporte_cdr_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}

/*function reporte_crd_block(){
	$blocks['reporte_cdr'] = array(
		'info' => t('reporte_cdr'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
		);
	return $blocks;
}

*/
	
function reporte_cdr_form($form,&$form_state){
		$form['tiempo_inicio'] = array(
		'#type' => 'date_popup',
		'#default_value' => '2015-11-02 00:00:00',
		'#date_format' => 'Y-m-d H:i:s',
		'#date_label_position' => 'within',
		'#date_timezone' => 'America/El_Salvador',		
		'#required' => TRUE,
		'#title' => 'Fecha inicio:' 	
			);
		
		$form['tiempo_final'] = array(
		'#type' => 'date_popup',
		'#default_value' => '2015-11-02 00:00:00',
		'#date_format' => 'Y-m-d H:i:s',
		'#date_label_position' => 'within',
		'#date_timezone' => 'America/El_Salvador',		
		'#required' => TRUE,
		'#title' => 'Fecha fin:' 	
			);


	$form['submit_button'] = array(
	'#type'=> 'submit',
	'#value'=> t('Consultar')
	);
	
	return $form;
        
	}
	function reporte_cdr_form_validate($form, &$form_state) {
		if(empty($form_state['values']['tiempo_inicio']))
			form_set_error('tiempo_inicio', 'Debe elegir un tiempo de inicio');
		else if(empty($form_state['values']['tiempo_final']))
			form_set_error('tiempo_fin', 'Debe elegir un tiempo de fin');
	
	}	

	function reporte_cdr_form_submit($form, &$form_state){
		drupal_set_message('El formulario se ha enviado exitosamente'); 
	}

/*	function reporte_cdr_form_alter(&$form, $form_state){
		$form['#submit'][] = 'reporte_cdr_custom_submission';
		
	}

	function reporte_cdr_custom_submission(&$form, &$form_state){
		$form_state['redirect'] = 'consulta.php';
	}*/

