<?php

/* 

Copyright (C) 2015  Ulises Abel Arias García

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/


// Este es para que exista un link en drupal

function reporte_cdr_menu() {
  $items = array();

  $items['formularios/reporte-cdr'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Consulta de CDR', //page title
    'description' => 'Formulario de consulta de CDR',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('reporte_cdr_form'), //put the name of the form here
    'access callback' => TRUE
    
  );

  return $items;
}

// El formulario
	
function reporte_cdr_form($form,&$form_state){
		
	//	if(!empty($form_state['page_num'] && $form_state['page_num'] == 2){
	//	  $form_state['results_table'] = reporte_get_table($form, $form_state);
	//	  drupal_render($form_state['result_table']);
	//	}
		
	//	$form_state['page_num']=1;
		
		$form = array();
		
		$form['consultar_fecha'] = array(
			'#type' => 'fieldset',
			'#title' => t('Ingrese el rango del que desea reporte'),
			'#descripcion' => t('Elija con el calendario')
		);

		
		$form['consultar_fecha']['tiempo_inicio'] = array(
		'#type' => 'date_popup',
		'#default_value' => date('Y-m-d H:i:s'),
		'#date_format' => 'Y-m-d H:i:s',
		'#date_label_position' => 'within',
		'#date_timezone' => 'America/El_Salvador',		
		'#required' => TRUE,
		'#title' => 'Fecha inicio:' 	
			);
		
		$form['consultar_fecha']['tiempo_final'] = array(
		'#type' => 'date_popup',
		'#default_value' => date('Y-m-d H:i:s'),
		'#date_format' => 'Y-m-d H:i:s',
		'#date_label_position' => 'within',
		'#date_timezone' => 'America/El_Salvador',		
		'#required' => TRUE,
		'#title' => 'Fecha fin:' 	
			);
		
		$form['consultar_fecha']['operador_origen']= array(
		'#type' => 'textfield',
		'#size' => 15,
		'#required' => FALSE,
		'#maxlenght' => 100,
		'#title' => 'Operador Origen:'
		);

		$form['consultar_fecha']['operador_destino']= array(
		'#type' => 'textfield',
		'#size' => 15,
		'#maxlenght' => 100,
		'#required' => FALSE,
		'#title' => 'Operador Destino:'
		);

	if(!empty($form_state['results_table'])){
		$form['results_table'] = array('#markup' => $form_state['results_table']);
	}

	$form['submit'] = array(
	'#type'=> 'submit',
	'#value'=> 'Enviar',
	);
	
	return $form;
        
	}


// Validación
	function reporte_cdr_form_validate($form, &$form_state) {
		if(empty($form_state['values']['tiempo_inicio']))
			form_set_error('tiempo_inicio', 'Debe elegir un tiempo de inicio');
		else if(empty($form_state['values']['tiempo_final']))
			form_set_error('tiempo_fin', 'Debe elegir un tiempo de fin');
			
	}	

// Envío
function reporte_cdr_form_submit($form, &$form_state){
	
	$form_state['results_table'] = reporte_get_table($form, $form_state);

	$form_state['rebuild'] = true;	
}




function reporte_get_table($form, $form_state){
	include 'config.inc';
	$inicio = $form_state['values']['tiempo_inicio'];
	$final = $form_state['values']['tiempo_final'];
//aqui se agregara el query	
	Database::addConnectionInfo('cderre', 'default', $database_info);
	
	db_set_active('cderre');

	//$resultado=db_query("SELECT trfvnt,osrc,duration FROM cdr WHERE calldate BETWEEN '$inicio' AND '$final'");
	
	$query= db_select('cdr', 'cdr')
		//->extend('PagerDefault')
		//->limit(30)
		->orderBy('calldate')
		->fields('cdr', array('calldate', 'clid', 'src', 'dst ','dcontext','channel','billsec', 'disposition') )
		->condition('calldate', array($inicio,$final), 'BETWEEN');
	$resultado=$query->execute()->fetchAll();

	db_set_active('default');
	
	
	$rows= array();
	
	foreach ($resultado as $v){
		$rows[]= array($v->calldate, $v->clid, $v->src, $v->dst, $v->dcontext, $v->channel, $v->billsec, $v->disposition);
	}
	
	$header = array('Hora','Caller ID','Num Origen','Num Destino', 'Context', 'Canal', 'Cobro', 'Liberación');
	$output = theme('table', array('header' => $header, 'rows' => $rows));
	$output .= theme('pager', array('element'=> 0));
	

	return $output;


}

/*	function reporte_cdr_form_alter(&$form, $form_state,$form_id){
		$form['#submit'][] = 'reporte_cdr_form_submit_handler';
		
	}

	function reporte_cdr_form_submit_handler($form, &$form_state){
		drupal_set_message("A trastear el submit");
		$form_state['redirect'] = 'consulta.php';
	}
*/
